[target.x86_64-unknown-linux-gnu]
#dockerfile = "cargo-cross/Dockerfile.x86_64-unknown-linux-gnu"
image = "cross-x86_64-unknown-linux-gnu"
# docker build -t cross-x86_64-unknown-linux-gnu -f cargo-cross/Dockerfile.x86_64-unknown-linux-gnu .

[target.i686-unknown-linux-gnu]
#dockerfile = "cargo-cross/Dockerfile.i686-unknown-linux-gnu"
image = "cross-i686-unknown-linux-gnu"
# docker build -t cross-i686-unknown-linux-gnu -f cargo-cross/Dockerfile.i686-unknown-linux-gnu .
