# Fire Dispatch Crisis - Emergency Dispatcher Story

[metadata]
id = "fire_dispatch"
version = "1.0"
author = "Crisis Game System"
description_key = "fire_dispatch_desc"

[name]
eng = "Fire Dispatch"
spa = "Despacho de Emergencia"

[description]
eng = "You are an emergency dispatcher receiving urgent fire calls. Every decision affects response times and lives at stake."
spa = "Eres un despachador de emergencias recibiendo llamadas urgentes de incendio. Cada decisión afecta los tiempos de respuesta y las vidas en riesgo."

[character_names]
male_eng = ["Dispatcher Tom Wilson", "Dispatcher Mark Stevens", "Dispatcher Alex Rodriguez", "Dispatcher Kevin Park", "Dispatcher Chris Thompson"]
female_eng = ["Dispatcher Sarah Miller", "Dispatcher Jessica Brown", "Dispatcher Ashley Davis", "Dispatcher Nicole Garcia", "Dispatcher Amanda Wright"]
male_spa = ["Despachador Carlos Mendoza", "Despachador Luis Jiménez", "Despachador Rafael Torres", "Despachador Eduardo Ramírez", "Despachador Andrés Morales"]
female_spa = ["Despachadora Patricia Vega", "Despachadora Monica Delgado", "Despachadora Claudia Sandoval", "Despachadora Rosa Martinez", "Despachadora Lucia Herrera"]

[story]
starting_scene = "incoming_call"
default_language = "eng"

[mechanics]
time_limit_minutes = 10
save_progress = true
allow_restart = true
track_decisions = true

[conditions]
variables = ["available_trucks", "response_time", "caller_panic_level", "fire_severity"]

[conditions.choice_effects]
"send_one_truck" = { available_trucks = -1 }
"send_three_trucks" = { available_trucks = -3 }
"full_response" = { available_trucks = -5 }

[scenes.incoming_call]
text.eng = "{character_name}, you're working the night shift at Central Emergency Dispatch. It's 2:47 AM when your console lights up with an incoming 911 call. You have 12 fire trucks available across the city. The caller sounds panicked: 'Help! There's a fire at my apartment building! I think it's spreading!'"
text.spa = "{character_name}, estás trabajando el turno nocturno en Despacho Central de Emergencias. Son las 2:47 AM cuando tu consola se ilumina con una llamada entrante al 911. Tienes 12 camiones de bomberos disponibles en la ciudad. La persona que llama suena en pánico: '¡Ayuda! ¡Hay un incendio en mi edificio de apartamentos! ¡Creo que se está extendiendo!'"
background_image = "Fire_Dispatch/background_from_firetruck_center.png"
speaking_character_image = "Fire_Dispatch/panicked_caller_character.png"

[[scenes.incoming_call.choices]]
text.eng = "Ask for specific location and floor"
text.spa = "Preguntar por ubicación específica y piso"
leads_to = "gather_details"

[[scenes.incoming_call.choices]]
text.eng = "Immediately dispatch one fire truck"
text.spa = "Despachar inmediatamente un camión de bomberos"
leads_to = "quick_dispatch"

[[scenes.incoming_call.choices]]
text.eng = "Ask about number of people potentially trapped"
text.spa = "Preguntar sobre número de personas potencialmente atrapadas"
leads_to = "assess_casualties"

[scenes.gather_details]
text.eng = "Caller: 'It's the Riverside Apartments on Oak Street! Third floor, but the smoke is getting thicker. I can see flames from the window!' You note this is a 6-story building with 48 units. Your database shows it's an older building without modern fire suppression systems."
text.spa = "Llamador: '¡Son los Apartamentos Riverside en Oak Street! Tercer piso, ¡pero el humo se está espesando. ¡Puedo ver llamas desde la ventana!' Notas que es un edificio de 6 pisos con 48 unidades. Tu base de datos muestra que es un edificio antiguo sin sistemas modernos de supresión de incendios."
background_image = "Fire_Dispatch/apartment_fire_background.png"
speaking_character_image = "Fire_Dispatch/frightened_caller_character.png"

[[scenes.gather_details.choices]]
text.eng = "Send standard response - 2 fire trucks"
text.spa = "Enviar respuesta estándar - 2 camiones de bomberos"
leads_to = "standard_response"

[[scenes.gather_details.choices]]
text.eng = "Send enhanced response - 4 trucks plus rescue unit"
text.spa = "Enviar respuesta mejorada - 4 camiones más unidad de rescate"
leads_to = "enhanced_response"

[[scenes.gather_details.choices]]
text.eng = "Send full alarm - 6 trucks, 2 rescue units, ambulances"
text.spa = "Enviar alarma completa - 6 camiones, 2 unidades de rescate, ambulancias"
leads_to = "full_alarm"

[scenes.quick_dispatch]
text.eng = "You dispatch Engine 7, the closest unit, which is 4 minutes away. As you're sending them, another call comes in: 'This is Engine 12, we're seeing heavy smoke from the Riverside Apartments while passing by. This looks bigger than a single unit can handle.'"
text.spa = "Despachas Bomba 7, la unidad más cercana, que está a 4 minutos. Mientras los envías, llega otra llamada: 'Habla Bomba 12, estamos viendo humo denso de los Apartamentos Riverside mientras pasamos. Esto parece más grande de lo que una sola unidad puede manejar.'"
speaking_character_image = "Fire_Dispatch/alarmed-firefighter.png"

[[scenes.quick_dispatch.choices]]
text.eng = "Send additional trucks immediately"
text.spa = "Enviar camiones adicionales inmediatamente"
leads_to = "reinforcements"

[[scenes.quick_dispatch.choices]]
text.eng = "Wait for Engine 7's assessment"
text.spa = "Esperar evaluación de Bomba 7"
leads_to = "wait_assessment"

[scenes.assess_casualties]
text.eng = "Caller: 'I don't know! It's late, most people should be sleeping. There are families with kids here. Oh God, I can hear someone screaming from down the hall!' The urgency in their voice increases. You can hear smoke alarms blaring in the background."
text.spa = "Llamador: '¡No sé! Es tarde, la mayoría de la gente debería estar durmiendo. Hay familias con niños aquí. ¡Dios mío, puedo escuchar a alguien gritando desde el pasillo!' La urgencia en su voz aumenta. Puedes escuchar alarmas de humo sonando de fondo."

[[scenes.assess_casualties.choices]]
text.eng = "Dispatch maximum response - all available units"
text.spa = "Despachar respuesta máxima - todas las unidades disponibles"
leads_to = "maximum_response"

[[scenes.assess_casualties.choices]]
text.eng = "Send major response but keep some units for other calls"
text.spa = "Enviar respuesta mayor pero mantener algunas unidades para otras llamadas"
leads_to = "balanced_response"

[scenes.standard_response]
text.eng = "You dispatch Engines 7 and 12 with Ladder 3. Total response time: 6 minutes. The crews arrive to find a working fire on the third floor with smoke showing from multiple windows. The incident commander radios: 'We need more resources - this is extending to the fourth floor.'"
text.spa = "Despachas Bombas 7 y 12 con Escalera 3. Tiempo total de respuesta: 6 minutos. Las cuadrillas llegan para encontrar un incendio activo en el tercer piso con humo visible desde múltiples ventanas. El comandante del incidente radía: 'Necesitamos más recursos - esto se está extendiendo al cuarto piso.'"
speaking_character_image = "Fire_Dispatch/alarmed-firefighter.png"
background_image = "Fire_Dispatch/standard_response.jpg"

[[scenes.standard_response.choices]]
text.eng = "Send additional units and call second alarm"
text.spa = "Enviar unidades adicionales y llamar segunda alarma"
leads_to = "second_alarm"

[[scenes.standard_response.choices]]
text.eng = "Send just two more trucks"
text.spa = "Enviar solo dos camiones más"
leads_to = "limited_backup"

[scenes.enhanced_response]
text.eng = "Your enhanced response arrives in waves: first units in 5 minutes, full response assembled in 8 minutes. The incident commander reports: 'Good call, dispatch. We have fire on floors 3 and 4, with multiple residents evacuated safely. We're getting ahead of this with the resources we have.'"
text.spa = "Tu respuesta mejorada llega en oleadas: primeras unidades en 5 minutos, respuesta completa en 8 minutos. El comandante del incidente reporta: 'Buena decisión, despacho. Tenemos fuego en pisos 3 y 4, con múltiples residentes evacuados de forma segura. Estamos controlando esto con los recursos que tenemos.'"
speaking_character_image = "Fire_Dispatch/alarmed-firefighter.png"

[[scenes.enhanced_response.choices]]
text.eng = "Maintain current response level"
text.spa = "Mantener nivel de respuesta actual"
leads_to = "controlled_situation"

[[scenes.enhanced_response.choices]]
text.eng = "Send additional ambulances for smoke inhalation"
text.spa = "Enviar ambulancias adicionales por inhalación de humo"
leads_to = "medical_support"

[scenes.controlled_situation]
text.eng = "Your decision proves correct. The fire is contained to two floors with no casualties. 23 residents are evacuated safely, and the fire is under control within 45 minutes. The incident commander commends your resource allocation: 'Perfect response level - we had exactly what we needed.'"
text.spa = "Tu decisión resulta correcta. El incendio se contiene en dos pisos sin víctimas. 23 residentes son evacuados de forma segura, y el incendio está bajo control en 45 minutos. El comandante del incidente elogia tu asignación de recursos: 'Nivel de respuesta perfecto - teníamos exactamente lo que necesitábamos.'"
speaking_character_image = "Fire_Dispatch/alarmed-firefighter.png"

[scenes.maximum_response]
text.eng = "You send everything: 8 fire trucks, 3 ladder companies, 4 rescue units, and 6 ambulances. The massive response overwhelms the small fire, which is quickly controlled. However, this leaves only 4 trucks available citywide, and two other fires start during the incident."
text.spa = "Envías todo: 8 camiones de bomberos, 3 compañías de escaleras, 4 unidades de rescate y 6 ambulancias. La respuesta masiva abruma al incendio pequeño, que se controla rápidamente. Sin embargo, esto deja solo 4 camiones disponibles en toda la ciudad, y otros dos incendios comienzan durante el incidente."

[[scenes.maximum_response.choices]]
text.eng = "Deal with resource shortage for other calls"
text.spa = "Lidiar con escasez de recursos para otras llamadas"
leads_to = "resource_crisis"

[scenes.reinforcements]
text.eng = "You quickly dispatch Engines 15, 22, and Ladder 8 to assist Engine 7. The combined response arrives within 7 minutes, and the incident commander radios: 'Good call on the additional units. We've got a working fire with potential for extension, but we're getting ahead of it now.'"
text.spa = "Despachas rápidamente Bombas 15, 22 y Escalera 8 para asistir a Bomba 7. La respuesta combinada llega en 7 minutos, y el comandante del incidente radía: 'Buena decisión con las unidades adicionales. Tenemos un incendio activo con potencial de extensión, pero ahora lo estamos controlando.'"
speaking_character_image = "Fire_Dispatch/alarmed-firefighter.png"

[[scenes.reinforcements.choices]]
text.eng = "Continue current response"
text.spa = "Continuar respuesta actual"
leads_to = "controlled_situation"

[scenes.wait_assessment]
text.eng = "You decide to wait for Engine 7's assessment. Three critical minutes pass before they radio: 'Engine 7 to dispatch, we have a working structure fire with heavy smoke showing. We need immediate backup - this is bigger than we can handle alone!'"
text.spa = "Decides esperar la evaluación de Bomba 7. Pasan tres minutos críticos antes de que radíen: '¡Bomba 7 a despacho, tenemos un incendio estructural activo con humo denso visible. Necesitamos refuerzos inmediatos - esto es más grande de lo que podemos manejar solos!'"
speaking_character_image = "Fire_Dispatch/alarmed-firefighter.png"

[[scenes.wait_assessment.choices]]
text.eng = "Send massive response now"
text.spa = "Enviar respuesta masiva ahora"
leads_to = "late_response"

[scenes.full_alarm]
text.eng = "You pull the full alarm: 6 trucks, 2 ladder companies, rescue squad, hazmat unit, and 4 ambulances respond. The massive response overwhelms the incident, containing it quickly but using nearly all your available resources."
text.spa = "Activas la alarma completa: 6 camiones, 2 compañías de escaleras, escuadrón de rescate, unidad de materiales peligrosos y 4 ambulancias responden. La respuesta masiva abruma el incidente, conteniéndolo rápidamente pero usando casi todos tus recursos disponibles."

[[scenes.full_alarm.choices]]
text.eng = "Monitor citywide coverage"
text.spa = "Monitorear cobertura de toda la ciudad"
leads_to = "resource_management"

[scenes.balanced_response]
text.eng = "You send 4 trucks, 1 ladder company, and 2 ambulances, keeping adequate resources for other emergencies. The response proves effective - the fire is contained with 18 residents evacuated safely."
text.spa = "Envías 4 camiones, 1 compañía de escaleras y 2 ambulancias, manteniendo recursos adecuados para otras emergencias. La respuesta resulta efectiva - el incendio se contiene con 18 residentes evacuados de forma segura."
speaking_character_image = "Fire_Dispatch/alarmed-firefighter.png"

[[scenes.balanced_response.choices]]
text.eng = "Mission accomplished"
text.spa = "Misión cumplida"
leads_to = "successful_outcome"

[scenes.second_alarm]
text.eng = "You call a second alarm, sending Engines 4, 18, 21, Ladder 11, and two additional ambulances. The incident commander radios: 'Second alarm units arriving on scene. We've got good knockdown on the fire and all residents accounted for.'"
text.spa = "Llamas una segunda alarma, enviando Bombas 4, 18, 21, Escalera 11 y dos ambulancias adicionales. El comandante del incidente radía: 'Unidades de segunda alarma llegando a la escena. Tenemos buen control del incendio y todos los residentes contabilizados.'"
speaking_character_image = "Fire_Dispatch/alarmed-firefighter.png"

[[scenes.second_alarm.choices]]
text.eng = "Continue monitoring"
text.spa = "Continuar monitoreando"
leads_to = "successful_outcome"

[scenes.limited_backup]
text.eng = "You send only Engines 9 and 16 as backup. The incident commander radios back: 'We're making progress but it's tight. The fire has extended to two more units. We could use one more truck if available.'"
text.spa = "Envías solo Bombas 9 y 16 como refuerzo. El comandante del incidente radía de vuelta: 'Estamos progresando pero está ajustado. El incendio se ha extendido a dos unidades más. Podríamos usar un camión más si está disponible.'"
speaking_character_image = "Fire_Dispatch/alarmed-firefighter.png"

[[scenes.limited_backup.choices]]
text.eng = "Send one more truck"
text.spa = "Enviar un camión más"
leads_to = "adequate_response"

[[scenes.limited_backup.choices]]
text.eng = "Hold resources for other calls"
text.spa = "Mantener recursos para otras llamadas"
leads_to = "stretched_resources"

[scenes.medical_support]
text.eng = "You dispatch Medic 7, Medic 12, and the Mass Casualty Unit. The additional medical resources prove valuable as 8 residents are treated for smoke inhalation, with 3 transported to the hospital for observation."
text.spa = "Despachas Médico 7, Médico 12 y la Unidad de Víctimas Masivas. Los recursos médicos adicionales resultan valiosos ya que 8 residentes son tratados por inhalación de humo, con 3 transportados al hospital para observación."

[[scenes.medical_support.choices]]
text.eng = "Monitor patient outcomes"
text.spa = "Monitorear resultados de pacientes"
leads_to = "medical_success"

[scenes.late_response]
text.eng = "The delayed response proves costly. By the time additional units arrive, the fire has extended to multiple floors. While eventually controlled, 5 residents require hospitalization for smoke inhalation, and property damage is extensive."
text.spa = "La respuesta tardía resulta costosa. Para cuando llegan las unidades adicionales, el incendio se ha extendido a múltiples pisos. Aunque eventualmente se controla, 5 residentes requieren hospitalización por inhalación de humo, y el daño a la propiedad es extenso."

[scenes.resource_management]
text.eng = "Your heavy resource commitment pays off - the fire is quickly controlled with no injuries. However, when two smaller fires break out during the incident, response is delayed due to limited available units."
text.spa = "Tu fuerte compromiso de recursos da resultado - el incendio se controla rápidamente sin lesiones. Sin embargo, cuando dos incendios menores estallan durante el incidente, la respuesta se retrasa debido a las unidades disponibles limitadas."

[scenes.successful_outcome]
text.eng = "Your strategic resource allocation proves excellent. The fire is contained with minimal property damage, all residents evacuated safely, and you maintain adequate citywide coverage for other emergencies."
text.spa = "Tu asignación estratégica de recursos resulta excelente. El incendio se contiene con daño mínimo a la propiedad, todos los residentes evacuados de forma segura, y mantienes cobertura adecuada en toda la ciudad para otras emergencias."

[scenes.adequate_response]
text.eng = "The additional truck makes the difference. The incident commander radios: 'That last unit helped us get control. Fire is knocked down, all residents safe. Good resource management, dispatch.'"
text.spa = "El camión adicional marca la diferencia. El comandante del incidente radía: 'Esa última unidad nos ayudó a tomar control. Incendio controlado, todos los residentes seguros. Buen manejo de recursos, despacho.'"
speaking_character_image = "Fire_Dispatch/alarmed-firefighter.png"

[scenes.stretched_resources]
text.eng = "Your decision to hold resources results in a longer fire suppression time. The incident commander manages with available units, but later reports: 'We got it done, but one more truck would have saved us 20 minutes and reduced property loss.'"
text.spa = "Tu decisión de mantener recursos resulta en un tiempo de supresión de incendios más largo. El comandante del incidente se las arregla con las unidades disponibles, pero luego reporta: 'Lo logramos, pero un camión más nos habría ahorrado 20 minutos y reducido la pérdida de propiedad.'"
speaking_character_image = "Fire_Dispatch/alarmed-firefighter.png"

[scenes.medical_success]
text.eng = "All smoke inhalation victims recover fully thanks to prompt medical care. The incident commander commends your foresight: 'The extra medical units made all the difference. Professional response all around.'"
text.spa = "Todas las víctimas de inhalación de humo se recuperan completamente gracias a la atención médica rápida. El comandante del incidente elogia tu previsión: 'Las unidades médicas adicionales marcaron toda la diferencia. Respuesta profesional en todos los aspectos.'"

[scenes.resource_crisis]
text.eng = "The other fires prove more serious due to delayed response from your resource shortage. While the apartment fire had no casualties, the warehouse fire across town spreads unchecked for 15 minutes, causing major property damage. You learn the hard lesson of balancing immediate response with citywide coverage."
text.spa = "Los otros incendios resultan más serios debido a la respuesta tardía por tu escasez de recursos. Mientras que el incendio del apartamento no tuvo víctimas, el incendio del almacén al otro lado de la ciudad se extiende sin control por 15 minutos, causando daños importantes a la propiedad. Aprendes la dura lección de equilibrar la respuesta inmediata con la cobertura de toda la ciudad."
