# Fire Dispatch Crisis - Emergency Dispatcher Story

[metadata]
id = "fire_dispatch"
version = "1.0"
author = "Crisis Game System"
description_key = "fire_dispatch_desc"

[name]
eng = "Fire Dispatch"
spa = "Despacho de Emergencia"

[description]
eng = "You are an emergency dispatcher receiving urgent fire calls. Every decision affects response times and lives at stake."
spa = "Eres un despachador de emergencias recibiendo llamadas urgentes de incendio. Cada decisión afecta los tiempos de respuesta y las vidas en riesgo."

[character_names]
male_eng = ["Dispatcher Tom Wilson", "Dispatcher Mark Stevens", "Dispatcher Alex Rodriguez", "Dispatcher Kevin Park", "Dispatcher Chris Thompson"]
female_eng = ["Dispatcher Sarah Miller", "Dispatcher Jessica Brown", "Dispatcher Ashley Davis", "Dispatcher Nicole Garcia", "Dispatcher Amanda Wright"]
male_spa = ["Despachador Carlos Mendoza", "Despachador Luis Jiménez", "Despachador Rafael Torres", "Despachador Eduardo Ramírez", "Despachador Andrés Morales"]
female_spa = ["Despachadora Patricia Vega", "Despachadora Monica Delgado", "Despachadora Claudia Sandoval", "Despachadora Rosa Martinez", "Despachadora Lucia Herrera"]

[story]
starting_scene = "incoming_call"
default_language = "eng"

[mechanics]
time_limit_minutes = 10
save_progress = true
allow_restart = true
track_decisions = true

[conditions]
variables = ["available_trucks", "response_time", "caller_panic_level", "fire_severity"]

[conditions.choice_effects]
"send_one_truck" = { available_trucks = -1 }
"send_three_trucks" = { available_trucks = -3 }
"full_response" = { available_trucks = -5 }