# Language Test Crisis - Testing Multi-language Support

[metadata]
id = "language_test"
version = "1.0"
author = "Crisis Game System"
description_key = "language_test_desc"

[name]
eng = "Language Test"
spa = "Prueba de Idioma" 
fra = "Test de Langue"
deu = "Sprachtest"

[description]
eng = "A simple test to verify that language switching works correctly in the crisis system."
spa = "Una prueba simple para verificar que el cambio de idioma funciona correctamente en el sistema de crisis."
fra = "Un test simple pour vérifier que le changement de langue fonctionne correctement dans le système de crise."
deu = "Ein einfacher Test zur Überprüfung, ob der Sprachwechsel im Krisensystem korrekt funktioniert."

[character_names]
male_eng = ["Alex", "John", "Mike", "David", "Chris"]
female_eng = ["Sarah", "Emma", "Lisa", "Anna", "Kate"]
male_spa = ["Carlos", "Miguel", "Diego", "Juan", "Pedro"]
female_spa = ["María", "Carmen", "Ana", "Elena", "Sofia"]
male_fra = ["Pierre", "Jean", "Michel", "Paul", "Louis"]
female_fra = ["Marie", "Claire", "Sophie", "Anne", "Julie"]
male_deu = ["Hans", "Klaus", "Wolfgang", "Helmut", "Günter"]
female_deu = ["Greta", "Ingrid", "Heidi", "Brunhilde", "Ursula"]

[story]
starting_scene = "intro"
default_language = "eng"

[mechanics]
time_limit_minutes = 5
save_progress = true
allow_restart = true
track_decisions = true

[conditions]
variables = ["test_score"]
choice_effects = {}

[scenes.intro]
text.eng = "Hello {character_name}! This is a test of the multi-language system. You should see this text in your selected language. The system automatically detected your preferred language, but you can change it in Settings."
text.spa = "¡Hola {character_name}! Esta es una prueba del sistema multiidioma. Deberías ver este texto en tu idioma seleccionado. El sistema detectó automáticamente tu idioma preferido, pero puedes cambiarlo en Configuración."
text.fra = "Bonjour {character_name}! Ceci est un test du système multilingue. Vous devriez voir ce texte dans votre langue sélectionnée. Le système a automatiquement détecté votre langue préférée, mais vous pouvez la changer dans les Paramètres."
text.deu = "Hallo {character_name}! Dies ist ein Test des mehrsprachigen Systems. Sie sollten diesen Text in Ihrer ausgewählten Sprache sehen. Das System hat automatisch Ihre bevorzugte Sprache erkannt, aber Sie können sie in den Einstellungen ändern."

[[scenes.intro.choices]]
text.eng = "Test the English fallback system"
text.spa = "Probar el sistema de respaldo en inglés"
text.fra = "Tester le système de repli anglais"
text.deu = "Das englische Fallback-System testen"
leads_to = "fallback_test"

[[scenes.intro.choices]]
text.eng = "Complete the language test"
text.spa = "Completar la prueba de idioma"
text.fra = "Terminer le test de langue"
text.deu = "Den Sprachtest beenden"
leads_to = "completion"

[scenes.fallback_test]
text.eng = "This scene has text in English, but if your language was set to something else and no translation existed, it would fall back to English automatically."
text.spa = "Esta escena tiene texto en inglés, pero si tu idioma estuviera configurado en algo más y no existiera traducción, automáticamente volvería al inglés."
text.fra = "Cette scène a du texte en anglais, mais si votre langue était réglée sur autre chose et qu'aucune traduction n'existait, elle reviendrait automatiquement à l'anglais."

[[scenes.fallback_test.choices]]
text.eng = "Return to start"
text.spa = "Volver al inicio"
text.fra = "Retourner au début"
leads_to = "intro"

[scenes.completion]
text.eng = "Congratulations {character_name}! The language system is working correctly. You can change your language preference in Settings and restart to see this story in different languages."
text.spa = "¡Felicidades {character_name}! El sistema de idiomas está funcionando correctamente. Puedes cambiar tu preferencia de idioma en Configuración y reiniciar para ver esta historia en diferentes idiomas."
text.fra = "Félicitations {character_name}! Le système de langue fonctionne correctement. Vous pouvez changer votre préférence de langue dans les Paramètres et redémarrer pour voir cette histoire dans différentes langues."
text.deu = "Herzlichen Glückwunsch {character_name}! Das Sprachsystem funktioniert korrekt. Sie können Ihre Sprachpräferenz in den Einstellungen ändern und neu starten, um diese Geschichte in verschiedenen Sprachen zu sehen."

[[scenes.completion.choices]]
text.eng = "Test again"
text.spa = "Probar de nuevo"
text.fra = "Tester à nouveau"
text.deu = "Erneut testen"
leads_to = "intro"