background_image = "Fire_Dispatch/command_center_monitoring.png"
speaking_character_image = "Fire_Dispatch/fire_chief_character.png"
background_audio = "Fire_Dispatch/fire-sound-effects-224089.mp3"

[text]
eng = "You request an evacuation status update. 'Dispatch to Engine 12, what's the status on building evacuation?' 'Engine 12 to Dispatch, building is approximately 70% evacuated, residents are being directed to the south parking lot, no injuries reported at this time. Third floor residents still exiting via stairwells.'"
spa = "Solicitas una actualización del estado de evacuación. 'Despacho a Camión 12, ¿cuál es el estado de la evacuación del edificio?' 'Camión 12 a Despacho, el edificio está aproximadamente 70% evacuado, los residentes están siendo dirigidos al estacionamiento sur, no se reportan heridas en este momento. Los residentes del tercer piso aún están saliendo por las escaleras.'"

[[choices]]
text.eng = "Continue monitoring evacuation progress"
text.spa = "Continuar monitoreando progreso de evacuación"
leads_to = "successful_outcome"

[[choices]]
text.eng = "Request additional personnel for crowd control"
text.spa = "Solicitar personal adicional para control de multitudes"
leads_to = "enhanced_response"

[[choices]]
text.eng = "Coordinate with Red Cross for displaced residents"
text.spa = "Coordinar con Cruz Roja para residentes desplazados"
leads_to = "citizen_assist"