background_image = "Fire_Dispatch/background_from_firetruck_center.png"
speaking_character_image = [
    "Fire_Dispatch/panicked_caller_character.png",
    "Fire_Dispatch/panicked_caller_character_2.png",
]

[text]
eng = "{character_name}, you're working the night shift at Central Emergency Dispatch. It's 2:47 AM when your console lights up with an incoming 911 call. You have 12 fire trucks available across the city. The caller sounds panicked: 'Help! There's a fire at my apartment building! I think it's spreading!'"
spa = "{character_name}, estás trabajando el turno nocturno en Despacho Central de Emergencias. Son las 2:47 AM cuando tu consola se ilumina con una llamada entrante al 911. Tienes 12 camiones de bomberos disponibles en la ciudad. La persona que llama suena en pánico: '¡Ayuda! ¡Hay un incendio en mi edificio de apartamentos! ¡Creo que se está extendiendo!'"


[[choices]]
text.eng = "Ask for specific location and floor"
text.spa = "Preguntar por ubicación específica y piso"
leads_to = "gather_details"

[[choices]]
text.eng = "Immediately dispatch one fire truck"
text.spa = "Despachar inmediatamente un camión de bomberos"
leads_to = "quick_dispatch"

[[choices]]
text.eng = "Ask about number of people potentially trapped"
text.spa = "Preguntar sobre número de personas potencialmente atrapadas"
leads_to = "assess_casualties"
