background_image = "Fire_Dispatch/apartment_fire_background.png"
speaking_character_image = "Fire_Dispatch/alarmed-firefighter.png"
background_audio = "Fire_Dispatch/fire-sound-effects-224089.mp3"

[text]
eng = "Your strategic resource allocation proves excellent. The fire is contained with minimal property damage, all residents evacuated safely, and you maintain adequate citywide coverage for other emergencies."
spa = "Tu asignación estratégica de recursos resulta excelente. El incendio se contiene con daño mínimo a la propiedad, todos los residentes evacuados de forma segura, y mantienes cobertura adecuada en toda la ciudad para otras emergencias."

