FROM ghcr.io/cross-rs/x86_64-unknown-linux-gnu:latest

RUN apt-get update && \
    apt-get install -y pkg-config libglib2.0-dev libgobject-2.0-dev && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
