FROM ghcr.io/cross-rs/i686-unknown-linux-gnu:latest

RUN dpkg --add-architecture i386 && \
    apt-get update && \
    apt-get install -y \
        pkg-config \
        libglib2.0-dev:i386 \
        libgobject-2.0-dev:i386 && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
